DROP TABLE IF EXISTS users, categories, events, part_requests, compilations, events_compilations CASCADE;

CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name  VARCHAR(250)                                        NOT NULL,
    email VARCHAR(254) UNIQUE                                 NOT NULL
);

CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name VARCHAR(255) UNIQUE                                 NOT NULL
);

CREATE TABLE IF NOT EXISTS events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    annotation         VARCHAR(2000)                                       NOT NULL,
    category_id        BIGINT REFERENCES categories (id) ON DELETE CASCADE NOT NULL,
    confirmed_requests BIGINT,
    created_on         TIMESTAMP WITHOUT TIME ZONE                         NOT NULL,
    description        VARCHAR(7000)                                       NOT NULL,
    event_date         TIMESTAMP WITHOUT TIME ZONE                         NOT NULL,
    initiator_id       BIGINT REFERENCES users (id) ON DELETE CASCADE      NOT NULL,
    lat                REAL                                                NOT NULL,
    lon                REAL                                                NOT NULL,
    paid               BOOLEAN                                             NOT NULL,
    participant_limit  BIGINT                                              NOT NULL,
    published_on       TIMESTAMP WITHOUT TIME ZONE,
    request_moderation BOOLEAN                                             NOT NULL,
    state              VARCHAR(32),
    title              VARCHAR(120)                                        NOT NULL,
    views              BIGINT

);

CREATE TABLE IF NOT EXISTS part_requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    event_id     BIGINT REFERENCES events (id) ON DELETE CASCADE     NOT NULL,
    requester_id BIGINT REFERENCES users (id) ON DELETE CASCADE      NOT NULL,
    created      TIMESTAMP WITHOUT TIME ZONE                         NOT NULL,
    status       VARCHAR(10)                                         NOT NULL,
    CONSTRAINT UQ_EVENT_WITH_REQUESTER UNIQUE (event_id, requester_id)

);

CREATE TABLE IF NOT EXISTS compilations
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    title  VARCHAR(128) UNIQUE                                 NOT NULL,
    pinned BOOL                                                NOT NULL
);

CREATE TABLE IF NOT EXISTS events_compilations
(
    event_id       BIGINT REFERENCES events (id) ON DELETE CASCADE       NOT NULL,
    compilation_id BIGINT REFERENCES compilations (id) ON DELETE CASCADE NOT NULL,
    PRIMARY KEY (event_id, compilation_id),
    CONSTRAINT UQ_EVENT_WITH_compilation UNIQUE (event_id, compilation_id)
);